name: CYM
on:
  release:
    types: [published]
    tag:
    - v1.*

jobs:
  build_and_upload:
    runs-on: ubuntu-latest

    
    steps:

      
      - name: CYM Checkout 
        uses: actions/checkout@v3

     
      - name: CYM Login 
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
    
      - name: CYM Install Docker
        uses: docker/setup-buildx-action@v1
      
    
      - name: CYM Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/randimg:${{ github.ref_name }}

    
      - name: CYM Post message 
        uses: bluenovaio/action-slack@main 
        with:
          username: "CYM"
          icon_emoji: ":robot_face:"
          text:  "${{secrets.SLACK_MSG}} \nRepo: ${{ github.repositoryUrl }}\nImage name: ${{ secrets.DOCKERHUB_USERNAME }}/randimg:${{github.ref_name}}\nImage url: https://hub.docker.com/repository/docker/candychu17/randimg"
          webhook_url: ${{ secrets.SLACK_WEBHOOK }}